// Liste des mots pour le jeu du pendu
const wordList = [
    { word: "pomme" }, { word: "poire" }, { word: "banane" }, { word: "fraise" }, { word: "framboise" },
    { word: "abricot" }, { word: "cerise" }, { word: "raisin" }, { word: "orange" }, { word: "citron" },
    { word: "pêche" }, { word: "prune" }, { word: "mangue" }, { word: "ananas" }, { word: "kiwi" },
    { word: "grenade" }, { word: "pamplemousse" }, { word: "clémentine" }, { word: "pomelo" }, { word: "mandarine" },
    { word: "ordinateur" }, { word: "clavier" }, { word: "souris" }, { word: "écran" }, { word: "imprimante" },
    { word: "tablette" }, { word: "téléphone" }, { word: "smartphone" }, { word: "télévision" }, { word: "console" },
    { word: "chaise" }, { word: "table" }, { word: "armoire" }, { word: "lit" }, { word: "canapé" },
    { word: "bureau" }, { word: "étagère" }, { word: "commode" }, { word: "buffet" }, { word: "meuble" },
    { word: "voiture" }, { word: "moto" }, { word: "vélo" }, { word: "trottinette" }, { word: "skateboard" },
    { word: "avion" }, { word: "hélicoptère" }, { word: "fusée" }, { word: "soucoupe" }, { word: "dirigeable" },
    { word: "bateau" }, { word: "voilier" }, { word: "sous-marin" }, { word: "paquebot" }, { word: "yacht" },
    { word: "train" }, { word: "métro" }, { word: "tramway" }, { word: "tgv" }, { word: "rer" },
    { word: "bus" }, { word: "taxi" }, { word: "uber" }, { word: "tram" }, { word: "funiculaire" },
    { word: "camion" }, { word: "remorque" }, { word: "tracteur" }, { word: "bulldozer" }, { word: "grue" },
    { word: "pelle" }, { word: "camionnette" }, { word: "fourgonnette" }, { word: "ambulance" }, { word: "pompier" },
    { word: "police" }, { word: "gendarmerie" }, { word: "samu" }, { word: "armée" }, { word: "militaire" },
    { word: "pompier" }, { word: "policier" }, { word: "gendarme" }, { word: "soldat" }, { word: "caporal" },
    { word: "sergent" }, { word: "lieutenant" }, { word: "capitaine" }, { word: "commandant" }, { word: "colonel" },
    { word: "général" }, { word: "amiral" }, { word: "maréchal" }, { word: "roi" }, { word: "reine" },
    { word: "prince" }, { word: "princesse" }, { word: "duc" }, { word: "duchesse" }, { word: "comte" },
    { word: "comtesse" }, { word: "baron" }, { word: "baronne" }, { word: "vicomte" }, { word: "vicomtesse" },
    { word: "marquis" }, { word: "marquise" }, { word: "empereur" }, { word: "impératrice" }, { word: "pape" },
    { word: "cardinal" }, { word: "évêque" }, { word: "prêtre" }, { word: "moine" }, { word: "religieux" },
    { word: "religieuse" }, { word: "cathédrale" }, { word: "église" }, { word: "basilique" }, { word: "chapelle" },
    { word: "mosquée" }, { word: "synagogue" }, { word: "temple" }, { word: "pagode" }, { word: "sanctuaire" },
    { word: "château" }, { word: "palais" }, { word: "manoir" }, { word: "forteresse" }, { word: "bastide" },
    { word: "villa" }, { word: "maison" }, { word: "appartement" }, { word: "studio" }, { word: "loft" },
    { word: "duplex" }, { word: "triplex" }, { word: "penthouse" }, { word: "mobilhome" }, { word: "caravane" },
    { word: "roulotte" }, { word: "tente" }, { word: "igloo" }, { word: "yourte" }, { word: "cabane" },
    { word: "chalet" }, { word: "cabanon" }, { word: "abri" }, { word: "refuge" }, { word: "garage" },
    { word: "jardin" }, { word: "parc" }, { word: "forêt" }, { word: "bois" }, { word: "verger" },
    { word: "potager" }, { word: "champ" }, { word: "prairie" }, { word: "plage" }, { word: "montagne" },
    { word: "colline" }, { word: "vallée" }, { word: "rivière" }, { word: "lac" }, { word: "étang" },
    { word: "cascade" }, { word: "torrent" }, { word: "ruisseau" }, { word: "fleuve" }, { word: "mer" },
    { word: "océan" }, { word: "continent" }, { word: "pays" }, { word: "région" }, { word: "département" },
    { word: "ville" }, { word: "village" }, { word: "hameau" }, { word: "quartier" }, { word: "rue" },
    { word: "avenue" }, { word: "boulevard" }, { word: "impasse" }, { word: "place" }, { word: "carrefour" },
    { word: "rond-point" }, { word: "pont" }, { word: "tunnel" }, { word: "passerelle" }, { word: "escalier" },
    { word: "ascenseur" }, { word: "couloir" }, { word: "porte" }, { word: "fenêtre" }, { word: "mur" },
    { word: "plafond" }, { word: "sol" }, { word: "toit" }, { word: "escalier" }, { word: "balcon" },
    { word: "terrasse" }, { word: "jardin" }, { word: "cour" }, { word: "allée" }, { word: "entrée" },
    { word: "sortie" }, { word: "salle" }, { word: "salon" }, { word: "cuisine" }, { word: "chambre" },
    { word: "salle-de-bain" }, { word: "toilettes" }, { word: "bureau" }, { word: "garage" }, { word: "cave" },
    { word: "grenier" }, { word: "buanderie" }, { word: "cellier" }, { word: "véranda" }, { word: "balcon" },
    { word: "anticonstitutionnellement" },
    { word: "intergouvernementalisations" },
    { word: "hippopotomonstrosesquippedaliophobie" },
    { word: "désinstitutionnalisation" },
    { word: "inconstitutionnellement" },
    { word: "psychopharmacothérapeutique" },
    { word: "immunohistochimiquement" },
    { word: "électroencéphalographiquement" },
    { word: "hexakosioihexekontahexaphobie" },
    { word: "phosphatidyléthanolamines" },
    { word: "thyroparathyroïdectomisées" },
    { word: "cyclopentanoperhydrophénanthrène" },
    { word: "sérendipité" },
    { word: "triskaïdékaphobie" },
    { word: "otorhinolaryngologiste" },
    { word: "anticonstitutionnel" },
    { word: "désintéressement" },
    { word: "incommensurable" },
    { word: "inintelligibilité" },
    { word: "immunodéficience" }
];
